/*
 * This file is auto-generated by Chargebee.
 * For more information on how to make changes to this file, please see the README.
 * Reach out to dx@chargebee.com for any questions.
 * Copyright 2026 Chargebee Inc.
 */

using System.Collections.Generic;

namespace ChargeBee.Telemetry
{
    /// <summary>
    /// Optional telemetry adapter for observability integrations (e.g. OpenTelemetry).
    ///
    /// When not configured, the SDK skips all telemetry work — zero overhead. The SDK stores the
    /// adapter by reference and never clones or deep-copies it.
    ///
    /// Implementations may inject W3C trace context headers (traceparent, tracestate)
    /// into requestHeaders during OnRequestStart.
    /// </summary>
    public interface ITelemetryAdapter
    {
        /// <summary>
        /// Called once per SDK API call before the request is sent (including before retries).
        /// </summary>
        /// <param name="context">Telemetry context with prebuilt start attributes.</param>
        /// <param name="requestHeaders">Mutable headers map for trace propagation injection.</param>
        /// <returns>An opaque handle passed back to OnRequestEnd, or null.</returns>
        object OnRequestStart(RequestTelemetryContext context, Dictionary<string, string> requestHeaders);

        /// <summary>
        /// Called once per SDK API call after the final response or terminal failure.
        /// </summary>
        /// <param name="handle">Value returned from OnRequestStart, may be null.</param>
        /// <param name="result">Telemetry result with prebuilt end attributes.</param>
        void OnRequestEnd(object handle, RequestTelemetryResult result);
    }
}
