/*
 * This file is auto-generated by Chargebee.
 * For more information on how to make changes to this file, please see the README.
 * Reach out to dx@chargebee.com for any questions.
 * Copyright 2026 Chargebee Inc.
 */

namespace ChargeBee.Telemetry
{
    /// <summary>
    /// Error details attached to RequestTelemetryResult on failed requests.
    /// </summary>
    public sealed class RequestTelemetryError
    {
        public RequestTelemetryError(
            string message,
            string chargebeeErrorCode = null,
            string chargebeeApiErrorType = null,
            string chargebeeErrorParam = null)
        {
            Message = message;
            ChargebeeErrorCode = chargebeeErrorCode;
            ChargebeeApiErrorType = chargebeeApiErrorType;
            ChargebeeErrorParam = chargebeeErrorParam;
        }

        public string Message { get; }
        public string ChargebeeErrorCode { get; }
        public string ChargebeeApiErrorType { get; }
        public string ChargebeeErrorParam { get; }
    }
}
