/*
 * This file is auto-generated by Chargebee.
 * For more information on how to make changes to this file, please see the README.
 * Reach out to dx@chargebee.com for any questions.
 * Copyright 2026 Chargebee Inc.
 */

using System.Collections.Generic;

namespace ChargeBee.Telemetry
{
    /// <summary>
    /// Context passed to ITelemetryAdapter.OnRequestStart.
    /// </summary>
    public sealed class RequestTelemetryContext
    {
        public RequestTelemetryContext(
            string spanName,
            string resource,
            string operation,
            string httpMethod,
            string httpUrl,
            string serverAddress,
            string chargebeeSite,
            string chargebeeApiVersion,
            string sdkName,
            string sdkVersion,
            Dictionary<string, string> startAttributes)
        {
            SpanName = spanName;
            Resource = resource;
            Operation = operation;
            HttpMethod = httpMethod;
            HttpUrl = httpUrl;
            ServerAddress = serverAddress;
            ChargebeeSite = chargebeeSite;
            ChargebeeApiVersion = chargebeeApiVersion;
            SdkName = sdkName;
            SdkVersion = sdkVersion;
            StartAttributes = startAttributes ?? new Dictionary<string, string>();
        }

        public string SpanName { get; }
        public string Resource { get; }
        public string Operation { get; }
        public string HttpMethod { get; }
        public string HttpUrl { get; }
        public string ServerAddress { get; }
        public string ChargebeeSite { get; }
        public string ChargebeeApiVersion { get; }
        public string SdkName { get; }
        public string SdkVersion { get; }
        public Dictionary<string, string> StartAttributes { get; }
    }
}
