/*
 * This file is auto-generated by Chargebee.
 * For more information on how to make changes to this file, please see the README.
 * Reach out to dx@chargebee.com for any questions.
 * Copyright 2026 Chargebee Inc.
 */

using System.Collections.Generic;

namespace ChargeBee.Telemetry
{
    /// <summary>
    /// Result passed to ITelemetryAdapter.OnRequestEnd.
    /// </summary>
    public sealed class RequestTelemetryResult
    {
        public RequestTelemetryResult(
            int httpStatusCode,
            long durationMs,
            RequestTelemetryError error,
            Dictionary<string, object> endAttributes)
        {
            HttpStatusCode = httpStatusCode;
            DurationMs = durationMs;
            Error = error;
            EndAttributes = endAttributes ?? new Dictionary<string, object>();
        }

        public int HttpStatusCode { get; }
        public long DurationMs { get; }
        public RequestTelemetryError Error { get; }
        public Dictionary<string, object> EndAttributes { get; }
    }
}
