/*
 * This file is auto-generated by Chargebee.
 * For more information on how to make changes to this file, please see the README.
 * Reach out to dx@chargebee.com for any questions.
 * Copyright 2026 Chargebee Inc.
 */

using System;
using System.Collections.Generic;
using ChargeBee.Api;

namespace ChargeBee.Telemetry
{
    /// <summary>
    /// Helpers for building standardized Chargebee telemetry context and results.
    /// </summary>
    public static class TelemetrySupport
    {
        public static string BuildSpanName(string resource, string operation)
        {
            return TelemetryAttributeKeys.TELEMETRY_SPAN_NAME_PREFIX + "." + resource + "." + operation;
        }

        public static string ResolveChargebeeApiVersion(string apiPath)
        {
            return apiPath == "/api/v1" ? "v1" : "v2";
        }

        public static Dictionary<string, string> BuildRequestStartSpanAttributes(
            string resource,
            string operation,
            string httpMethod,
            string httpUrl,
            string serverAddress,
            string chargebeeSite,
            string chargebeeApiVersion,
            string sdkVersion,
            Dictionary<string, string> requestHeaders = null)
        {
            var attributes = new Dictionary<string, string>
            {
                { TelemetryAttributeKeys.URL_FULL, httpUrl },
                { TelemetryAttributeKeys.HTTP_REQUEST_METHOD, httpMethod },
                { TelemetryAttributeKeys.SERVER_ADDRESS, serverAddress },
                { TelemetryAttributeKeys.CHARGEBEE_SITE, chargebeeSite },
                { TelemetryAttributeKeys.CHARGEBEE_API_VERSION, chargebeeApiVersion },
                { TelemetryAttributeKeys.CHARGEBEE_RESOURCE, resource },
                { TelemetryAttributeKeys.CHARGEBEE_OPERATION, operation },
                { TelemetryAttributeKeys.CHARGEBEE_SDK_NAME, TelemetryAttributeKeys.SDK_NAME },
                { TelemetryAttributeKeys.CHARGEBEE_SDK_VERSION, sdkVersion },
            };
            foreach (var entry in BuildRequestHeaderSpanAttributes(requestHeaders))
            {
                attributes[entry.Key] = entry.Value;
            }
            return attributes;
        }

        /// <summary>
        /// Promotes chargebee-* request headers to http.request.header.* attributes; excludes the chargebee-request-origin-* PII family.
        /// </summary>
        public static Dictionary<string, string> BuildRequestHeaderSpanAttributes(Dictionary<string, string> requestHeaders)
        {
            var attributes = new Dictionary<string, string>();
            if (requestHeaders == null)
            {
                return attributes;
            }

            foreach (var entry in requestHeaders)
            {
                if (entry.Key == null || entry.Value == null)
                {
                    continue;
                }
                var lowerName = entry.Key.ToLowerInvariant();
                if (!lowerName.StartsWith(TelemetryAttributeKeys.CHARGEBEE_TELEMETRY_HEADER_PREFIX)
                    || lowerName.StartsWith(TelemetryAttributeKeys.CHARGEBEE_TELEMETRY_HEADER_EXCLUDE_PREFIX))
                {
                    continue;
                }
                attributes[TelemetryAttributeKeys.HTTP_REQUEST_HEADER_ATTRIBUTE_PREFIX + lowerName] = entry.Value;
            }

            return attributes;
        }

        public static Dictionary<string, object> BuildRequestEndSpanAttributes(int httpStatusCode, RequestTelemetryError error)
        {
            var attributes = new Dictionary<string, object>
            {
                { TelemetryAttributeKeys.HTTP_RESPONSE_STATUS_CODE, httpStatusCode },
            };

            if (error != null)
            {
                if (!string.IsNullOrEmpty(error.ChargebeeApiErrorType))
                {
                    attributes[TelemetryAttributeKeys.ERROR_TYPE] = error.ChargebeeApiErrorType;
                    attributes[TelemetryAttributeKeys.CHARGEBEE_ERROR_TYPE] = error.ChargebeeApiErrorType;
                }
                if (!string.IsNullOrEmpty(error.ChargebeeErrorCode))
                {
                    attributes[TelemetryAttributeKeys.CHARGEBEE_ERROR_CODE] = error.ChargebeeErrorCode;
                }
                if (!string.IsNullOrEmpty(error.ChargebeeErrorParam))
                {
                    attributes[TelemetryAttributeKeys.CHARGEBEE_ERROR_PARAM] = error.ChargebeeErrorParam;
                }
            }
            return attributes;
        }

        public static RequestTelemetryContext BuildRequestTelemetryContext(
            string resource,
            string operation,
            string httpMethod,
            string httpUrl,
            string serverAddress,
            string chargebeeSite,
            string chargebeeApiVersion,
            string sdkVersion,
            Dictionary<string, string> requestHeaders = null)
        {
            return new RequestTelemetryContext(
                BuildSpanName(resource, operation),
                resource,
                operation,
                httpMethod,
                httpUrl,
                serverAddress,
                chargebeeSite,
                chargebeeApiVersion,
                TelemetryAttributeKeys.SDK_NAME,
                sdkVersion,
                BuildRequestStartSpanAttributes(
                    resource, operation, httpMethod, httpUrl, serverAddress, chargebeeSite, chargebeeApiVersion, sdkVersion, requestHeaders));
        }

        public static RequestTelemetryResult BuildRequestTelemetryResult(
            int httpStatusCode, long durationMs, RequestTelemetryError error)
        {
            return new RequestTelemetryResult(
                httpStatusCode,
                durationMs,
                error,
                BuildRequestEndSpanAttributes(httpStatusCode, error));
        }

        public static RequestTelemetryError ExtractRequestTelemetryError(Exception err)
        {
            if (err == null)
            {
                return null;
            }

            var message = string.IsNullOrEmpty(err.Message) ? "Chargebee API request failed" : err.Message;
            var apiException = err as ApiException;
            if (apiException != null)
            {
                return new RequestTelemetryError(
                    message,
                    apiException.ApiErrorCode,
                    apiException.Type,
                    apiException.Param);
            }

            return new RequestTelemetryError(message);
        }

        public static int? ExtractHttpStatusCode(Exception err)
        {
            var apiException = err as ApiException;
            if (apiException == null)
            {
                return null;
            }
            return (int)apiException.HttpStatusCode;
        }
    }
}
