/*
 * This file is auto-generated by Chargebee.
 * For more information on how to make changes to this file, please see the README.
 * Reach out to dx@chargebee.com for any questions.
 * Copyright 2026 Chargebee Inc.
 */

namespace ChargeBee.Telemetry
{
    /// <summary>
    /// Span attribute keys shared across Chargebee SDKs.
    /// </summary>
    public static class TelemetryAttributeKeys
    {
        public const string SDK_NAME = "chargebee-dotnet";
        public const string TELEMETRY_SPAN_NAME_PREFIX = "chargebee";

        public const string HTTP_REQUEST_HEADER_ATTRIBUTE_PREFIX = "http.request.header.";
        public const string CHARGEBEE_TELEMETRY_HEADER_PREFIX = "chargebee-";
        public const string CHARGEBEE_TELEMETRY_HEADER_EXCLUDE_PREFIX = "chargebee-request-origin-";

        public const string URL_FULL = "url.full";
        public const string HTTP_REQUEST_METHOD = "http.request.method";
        public const string HTTP_RESPONSE_STATUS_CODE = "http.response.status_code";
        public const string SERVER_ADDRESS = "server.address";
        public const string ERROR_TYPE = "error.type";
        public const string CHARGEBEE_SITE = "chargebee.site";
        public const string CHARGEBEE_API_VERSION = "chargebee.api_version";
        public const string CHARGEBEE_RESOURCE = "chargebee.resource";
        public const string CHARGEBEE_OPERATION = "chargebee.operation";
        public const string CHARGEBEE_SDK_NAME = "chargebee.sdk.name";
        public const string CHARGEBEE_SDK_VERSION = "chargebee.sdk.version";
        public const string CHARGEBEE_ERROR_CODE = "chargebee.error.code";
        public const string CHARGEBEE_ERROR_TYPE = "chargebee.error.type";
        public const string CHARGEBEE_ERROR_PARAM = "chargebee.error.param";
    }
}
